### ISSUE TITLE
mosaic78, einen Zwischenschritt einsparen

### ISSUE THREAD

**Issue by Muesgen** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18#3]
crop7 und crop8 haben keinen weißen Streifen. Ihr könntet daher den schritt mosaic78 sparen. Bei Merge könntet ihr dann mosaic34, mosaic56, crop7 und crop8 auswählen.

**Comment by johnfurie** [comment]
you're right, we changed it
