### ISSUE TITLE
Kommentar Assignment 02

### ISSUE THREAD

**Issue by eikeschott** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18#4]
Gute Ausführung, "Problem" wurde gelöst.
Teilweise wäre es einfacher mit lapply() oder for-loops zu arbeiten, statt den gleichen code acht mal immer für die nächste Datei auszuführen aber am Ende kommt es aufs gleiche raus.

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/blob/711c02bd4898e7ae319819ca2f86f0ae4dbc5865/doc/rs/assignment_02.Rmd#L72

hier verstehe ich leider nicht ganz wieso das gemacht wird, weil die Bilder 7 und 8 einwandfrei sind und keine "Streifen" entfernt werden müssen. Hier könnte man also RAM und Zeit sparen.

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/blob/711c02bd4898e7ae319819ca2f86f0ae4dbc5865/doc/rs/assignment_02.Rmd#L101

Hier habt ihr dann leider kein Endprodukt zum anschauen mehr mit drin. Das könnte man relativ einfach mit plotRGB(brick(PFADZUBILD)) lösen ohne den ganzen Code oben beim Knitten ausführen zu müssen.

**Comment by johnfurie** [comment]
> Gute Ausführung, "Problem" wurde gelöst.
> Teilweise wäre es einfacher mit lapply() oder for-loops zu arbeiten, statt den gleichen code acht mal immer für die nächste Datei auszuführen aber am Ende kommt es aufs gleiche raus.
> 
correct! due to RAM issues we were't able to write it with loops... corrected version follows 

> [mpg-envinfosys-teams-2018-envimaster_rs_18/doc/rs/assignment_02.Rmd](https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/blob/711c02bd4898e7ae319819ca2f86f0ae4dbc5865/doc/rs/assignment_02.Rmd#L72)
> 
> Line 72 in [711c02b](/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/commit/711c02bd4898e7ae319819ca2f86f0ae4dbc5865)
> 
>  mosaic78 = mosaic(crop7, crop8, fun=min) 
> hier verstehe ich leider nicht ganz wieso das gemacht wird, weil die Bilder 7 und 8 einwandfrei sind und keine "Streifen" entfernt werden müssen. Hier könnte man also RAM und Zeit sparen.
> 
Right!

> [mpg-envinfosys-teams-2018-envimaster_rs_18/doc/rs/assignment_02.Rmd](https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/blob/711c02bd4898e7ae319819ca2f86f0ae4dbc5865/doc/rs/assignment_02.Rmd#L101)
> 
> Line 101 in [711c02b](/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/commit/711c02bd4898e7ae319819ca2f86f0ae4dbc5865)
> 
>  plotRGB(imgfinal) 
> Hier habt ihr dann leider kein Endprodukt zum anschauen mehr mit drin. Das könnte man relativ einfach mit plotRGB(brick(PFADZUBILD)) lösen ohne den ganzen Code oben beim Knitten ausführen zu müssen.

Thanks for the tip
