### ISSUE TITLE
Falsches argument?

### ISSUE THREAD

**Issue by eikeschott** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18#7]
https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/blob/9b1c581844f206d7182425b3bf129dddbb86b6e5/src/001_short_scripts/a009_model_final.R#L72

Ist das nicht wieder die falsche Variable?
trControl wäre die richtige nicht trainControl.

https://www.rdocumentation.org/packages/CAST/versions/0.3.1/topics/ffs

**Comment by kfrac** [comment]
Ja, du hast schon recht, dass trainControl die falsche Variable ist. Zum Glück haben wir diese Fehler  nicht zweimal in Folge gemacht -- unser endgültiges Modell wird in einem anderen script ([000_run_scripts/model_final.R](https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-envimaster_rs_18/blob/9b1c581844f206d7182425b3bf129dddbb86b6e5/src/000_run_scripts/model_final.R)) trainiert. 

Wir wollen die Ordner noch aufräumen. Danke für die Anmerkung!
